# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.api.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()

    def tearDown(self) -> None:
        pass

    def test_get_live_health(self) -> None:
        """Test case for get_live_health

        """
        pass

    def test_get_readiness(self) -> None:
        """Test case for get_readiness

        """
        pass


if __name__ == '__main__':
    unittest.main()
