# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.models.device_update import DeviceUpdate

class TestDeviceUpdate(unittest.TestCase):
    """DeviceUpdate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeviceUpdate:
        """Test DeviceUpdate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeviceUpdate`
        """
        model = DeviceUpdate()
        if include_optional:
            return DeviceUpdate(
                firmware_release_id = '',
                name = '',
                metadata = { }
            )
        else:
            return DeviceUpdate(
        )
        """

    def testDeviceUpdate(self):
        """Test DeviceUpdate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
