# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.api.commands_api import CommandsApi


class TestCommandsApi(unittest.TestCase):
    """CommandsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = CommandsApi()

    def tearDown(self) -> None:
        pass

    def test_create_device_command(self) -> None:
        """Test case for create_device_command

        """
        pass

    def test_get_device_command(self) -> None:
        """Test case for get_device_command

        """
        pass

    def test_list_device_commands(self) -> None:
        """Test case for list_device_commands

        """
        pass


if __name__ == '__main__':
    unittest.main()
