# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.models.health import Health

class TestHealth(unittest.TestCase):
    """Health unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Health:
        """Test Health
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Health`
        """
        model = Health()
        if include_optional:
            return Health(
                status = 'ok'
            )
        else:
            return Health(
                status = 'ok',
        )
        """

    def testHealth(self):
        """Test Health"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
