# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers.

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.models.command_page import CommandPage

class TestCommandPage(unittest.TestCase):
    """CommandPage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CommandPage:
        """Test CommandPage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CommandPage`
        """
        model = CommandPage()
        if include_optional:
            return CommandPage(
                items = [
                    corelink_sdk.models.command.Command(
                        command_id = '',
                        tenant_id = '',
                        corelink_device_id = '',
                        command_type = '',
                        payload = { },
                        status = 'queued',
                        attempt_count = 56,
                        timeout_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        acknowledged_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        error_code = '',
                        metadata = { },
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                limit = 56,
                offset = 56
            )
        else:
            return CommandPage(
                items = [
                    corelink_sdk.models.command.Command(
                        command_id = '',
                        tenant_id = '',
                        corelink_device_id = '',
                        command_type = '',
                        payload = { },
                        status = 'queued',
                        attempt_count = 56,
                        timeout_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        acknowledged_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        completed_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        error_code = '',
                        metadata = { },
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                limit = 56,
                offset = 56,
        )
        """

    def testCommandPage(self):
        """Test CommandPage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
