# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.models.device_page import DevicePage

class TestDevicePage(unittest.TestCase):
    """DevicePage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DevicePage:
        """Test DevicePage
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DevicePage`
        """
        model = DevicePage()
        if include_optional:
            return DevicePage(
                items = [
                    corelink_sdk.models.device.Device(
                        corelink_device_id = '', 
                        tenant_id = '', 
                        device_model_id = '', 
                        partner_sku_id = '', 
                        firmware_release_id = '', 
                        name = '', 
                        status = 'inventory', 
                        metadata = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                limit = 56,
                offset = 56
            )
        else:
            return DevicePage(
                items = [
                    corelink_sdk.models.device.Device(
                        corelink_device_id = '', 
                        tenant_id = '', 
                        device_model_id = '', 
                        partner_sku_id = '', 
                        firmware_release_id = '', 
                        name = '', 
                        status = 'inventory', 
                        metadata = { }, 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                total = 56,
                limit = 56,
                offset = 56,
        )
        """

    def testDevicePage(self):
        """Test DevicePage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
