# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from corelink_sdk.api.devices_api import DevicesApi


class TestDevicesApi(unittest.TestCase):
    """DevicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DevicesApi()

    def tearDown(self) -> None:
        pass

    def test_create_device(self) -> None:
        """Test case for create_device

        """
        pass

    def test_get_device(self) -> None:
        """Test case for get_device

        """
        pass

    def test_list_devices(self) -> None:
        """Test case for list_devices

        """
        pass

    def test_update_device(self) -> None:
        """Test case for update_device

        """
        pass


if __name__ == '__main__':
    unittest.main()
