# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from corelink_sdk.models.command_status import CommandStatus
from typing import Optional, Set
from typing_extensions import Self

class Command(BaseModel):
    """
    Command
    """ # noqa: E501
    command_id: StrictStr
    tenant_id: StrictStr
    corelink_device_id: StrictStr
    command_type: StrictStr
    payload: Dict[str, Any]
    status: CommandStatus
    attempt_count: StrictInt
    timeout_at: Optional[datetime] = None
    acknowledged_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    metadata: Dict[str, Any]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["command_id", "tenant_id", "corelink_device_id", "command_type", "payload", "status", "attempt_count", "timeout_at", "acknowledged_at", "completed_at", "metadata", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Command from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if timeout_at (nullable) is None
        # and model_fields_set contains the field
        if self.timeout_at is None and "timeout_at" in self.model_fields_set:
            _dict['timeout_at'] = None

        # set to None if acknowledged_at (nullable) is None
        # and model_fields_set contains the field
        if self.acknowledged_at is None and "acknowledged_at" in self.model_fields_set:
            _dict['acknowledged_at'] = None

        # set to None if completed_at (nullable) is None
        # and model_fields_set contains the field
        if self.completed_at is None and "completed_at" in self.model_fields_set:
            _dict['completed_at'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Command from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "command_id": obj.get("command_id"),
            "tenant_id": obj.get("tenant_id"),
            "corelink_device_id": obj.get("corelink_device_id"),
            "command_type": obj.get("command_type"),
            "payload": obj.get("payload"),
            "status": obj.get("status"),
            "attempt_count": obj.get("attempt_count"),
            "timeout_at": obj.get("timeout_at"),
            "acknowledged_at": obj.get("acknowledged_at"),
            "completed_at": obj.get("completed_at"),
            "metadata": obj.get("metadata"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


