# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from corelink_sdk.models.device_status import DeviceStatus
from typing import Optional, Set
from typing_extensions import Self

class Device(BaseModel):
    """
    Device
    """ # noqa: E501
    corelink_device_id: StrictStr
    tenant_id: StrictStr
    device_model_id: StrictStr
    partner_sku_id: Optional[StrictStr] = None
    firmware_release_id: Optional[StrictStr] = None
    name: Optional[Annotated[str, Field(strict=True, max_length=255)]] = None
    status: DeviceStatus
    metadata: Dict[str, Any]
    created_at: datetime
    updated_at: datetime
    __properties: ClassVar[List[str]] = ["corelink_device_id", "tenant_id", "device_model_id", "partner_sku_id", "firmware_release_id", "name", "status", "metadata", "created_at", "updated_at"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of Device from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if partner_sku_id (nullable) is None
        # and model_fields_set contains the field
        if self.partner_sku_id is None and "partner_sku_id" in self.model_fields_set:
            _dict['partner_sku_id'] = None

        # set to None if firmware_release_id (nullable) is None
        # and model_fields_set contains the field
        if self.firmware_release_id is None and "firmware_release_id" in self.model_fields_set:
            _dict['firmware_release_id'] = None

        # set to None if name (nullable) is None
        # and model_fields_set contains the field
        if self.name is None and "name" in self.model_fields_set:
            _dict['name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of Device from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "corelink_device_id": obj.get("corelink_device_id"),
            "tenant_id": obj.get("tenant_id"),
            "device_model_id": obj.get("device_model_id"),
            "partner_sku_id": obj.get("partner_sku_id"),
            "firmware_release_id": obj.get("firmware_release_id"),
            "name": obj.get("name"),
            "status": obj.get("status"),
            "metadata": obj.get("metadata"),
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at")
        })
        return _obj


