# coding: utf-8

"""
    CoreLink Public API

    Versioned public contract for the proven connected-device slice. Integration details are deliberately excluded. All resource identifiers are canonical CoreLink identifiers. 

    The version of the OpenAPI document: 1.0.0-draft
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class DeviceStatus(str, Enum):
    """
    DeviceStatus
    """

    """
    allowed enum values
    """
    INVENTORY = 'inventory'
    PROVISIONING = 'provisioning'
    ACTIVE = 'active'
    SUSPENDED = 'suspended'
    RETIRED = 'retired'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of DeviceStatus from a JSON string"""
        return cls(json.loads(json_str))


